name: ec2 Nginx Deployment
on:
  push:
    branches:
      - main  
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/tmp/ec2_nginx"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo yum update -y
            sudo amazon-linux-extras enable nginx1
            sudo yum install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/ec2_nginx/* /usr/share/nginx/html/